sudo: required

arch:
  - arm64
os: linux

language: generic

services:
  - docker

before_install:
  - docker build -t moussavdb/build-graalvm-arm64:latest -t moussavdb/build-graalvm-arm64:build_$TRAVIS_BUILD_NUMBER .
script:
  - docker images moussavdb/build-graalvm-arm64
  
after_success:
  - docker login -u="moussavdb" -p="$DOCKER_PASSWORD";
    docker push moussavdb/build-graalvm-arm64:latest;
    docker push moussavdb/build-graalvm-arm64:$TRAVIS_BUILD_NUMBER;
